name: Dispatch

on:
  issues:
    types: 
      - opened

jobs:
  parse-issue-title:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.parse-title.outputs.result }}
    steps:
      - name: Parse issue title
        id: parse-title
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = "${{ github.event.issue.number }}";
            const issueTitle = "${{ github.event.issue.title }}".toLowerCase();
            return issueTitle;
          result-encoding: string

  dispatch-to-handler:
    needs: [parse-issue-title]
    runs-on: ubuntu-latest
    if: needs.parse-issue-title.outputs.result != 'none'

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
        
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r .github/workflows/requirements.txt

      - name: Create repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CREATE_TOKEN }}
          script: |
            github.rest.repos.createInOrg({
              org: "kex-24",
              name: "${{ needs.parse-issue-title.outputs.result }}"
            });
